[project]
name = "linguistic-maze"
version = "0.1.0"
description = "Игра-лабиринт для студентов-лингвистов"
authors = [
    {name = "FPL23", email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "pygame>=2.6.1",
    "transformers>=5.3.0",
    "torch>=2.10.0",
    "accelerate>=1.13.0",
    "mawo_pymorphy3>=1.0.4",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pylint (>=4.0.5,<5.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[tool.pylint]
disable = ['C0415', 'C0209',
    'E0611', 'E0401', 'E0602', 'E0015',
    'R1705', 'R1729', 'R0902', 'R0904', 'R0903', 'R0801', 'R0401',
    'W0511', 'W1309', 'W0120']
max-line-length = 130
max-statements = 90
max-branches = 40
max-locals = 20
max-nested-blocks = 10
max-positional-arguments = 10


[tool.pylint."messages control"]
disable = [
    "missing-module-docstring",
    "missing-function-docstring",
    "missing-class-docstring",
    "wildcard-import",
    "broad-exception-caught",
    'attribute-defined-outside-init',
    'no-member',
    'pointless-string-statement',
    'unidiomatic-typecheck',
    'line-too-long',
    'too-many-arguments',
    'assignment-from-no-return',
    'unnecessary-pass',
    'unused-variable',
    'unused-argument'
]

[tool.pylint."import"]
bad-function-names = ["*"]
